"""Build the sourced Wenyu day-trip page; no live prices or GPS inferred."""
from pathlib import Path
import json
from html import escape as e
from urllib.parse import quote
ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT/'data/wenyu-dining-research.json').read_text())
assert data['candidate_count'] == len(data['candidates']) == 4
assert len({x['id'] for x in data['candidates']}) == 4
OFFICIAL='https://www.beijing.gov.cn/fuwu/bmfw/sy/jrts/202608/t20260820_4830458.html'
REPORT='https://xinwen.bjd.com.cn/content/s6a86ac84e4b0e45f3fd6436a.html'
def nav(name):
    return 'https://uri.amap.com/search?keyword='+quote(name)+'&city=北京&view=map'
def button(name,label=None):
    return f'<a class="action" href="{e(nav(name))}" target="_blank" rel="noopener">{e(label or name)} ↗</a>'
cards=[]
for id in ['meizhou-beiyuan-huamao','redsun-laiguangying','double-u-wenyu','shicao-wenyu']:
    c=next(x for x in data['candidates'] if x['id']==id)
    sources=' · '.join(f'<a href="{e(s["url"])}" target="_blank" rel="noopener">{e(s["publisher"])}</a>（{e(s["source_date"])}；索引抓取 {e(s["crawled_at"])}）' for s in c['sources'])
    cards.append(f'''<article class="merchant" id="{id}">
<h3>{e(c['name'])}</h3><p class="orange">{e(c['role'])}</p>
<p><strong>{e(c['rating'])}</strong> · 人均：{e(c['average_cost_per_person'])}</p>
<dl><dt>地址</dt><dd>{e(c['address'])}</dd><dt>营业参考</dt><dd>{e(c['opening_hours'])}</dd><dt>吃什么 / 休息</dt><dd>{e('、'.join(c['menu_evidence']))}。{e(c['family_use'])}</dd><dt>空间与停车</dt><dd>{e(c['indoor_seating'])}；{e(c['parking'])}</dd><dt>和骑行区的关系</dt><dd>{e(c['gate_and_parking_relation'])}</dd><dt>用前确认</dt><dd>{e(c['priority'])}。当天营业、座位和实际车程未核；不宣称到店几分钟。</dd></dl>
{button(c['name'],'地图搜店（核对地址）')}<p class="source">证据：{sources}</p></article>''')
rows=[('08:30—09:30',60,'五道口 → 温榆河公园 P20停车场','单程预留1小时，估算非实时导航；P20满位改P21，不在路边卸车。'),('09:30—09:45',15,'卸车、头盔、厕所、看入口导览','停车区推行；向工作人员确认当天开放绿道和最近厕所。'),('09:45—10:30',45,'第一段：20号门内开放小环 / 原路折返','只循允许骑行的现场标识；确认能闭合再绕圈，否则原路返回。'),('10:30—10:45',15,'离开主路停靠，补水和点心','不在弯道、坡底、河岸边缘停车。无需依赖商店营业。'),('10:45—11:30',45,'第二段：同片区续骑，原入口收车','按体力重复已确认的小环，或在安全可停处折返；不以刷里程为目标。'),('11:30—11:45',15,'回P20装车','P21出发则回P21；不跨公共道路串园。'),('11:45—12:15',30,'驾车去午餐点 / 园内野餐准备','30分钟是接驳预留，不是餐厅实测车程；先看导航和营业。'),('12:15—13:30',75,'午餐＋坐下休息','主推眉州东坡；中餐备选红太阳；晴好可自带野餐。'),('13:30—14:30',60,'返回五道口','预留1小时，堵车顺延；若加咖啡再多留0.75—1小时。')]
assert sum(x[1] for x in rows)==360
schedule=''.join(f'<tr><td>{a}<br><small>{b/60:.2f}h</small></td><td><strong>{c}</strong></td><td>{d}</td></tr>' for a,b,c,d in rows)
page='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>五道口 → 温榆河骑行｜停车、园内路线与午餐休息</title><meta name="description" content="五道口自驾到温榆河公园P20/P21，园内亲子分段骑行，配官方开放地图、午餐与休息备选、来源与安全边界。"><style>
:root{--ink:#253d35;--muted:#67786e;--paper:#f5f4ed;--line:#dce4da;--accent:#d65e2f}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.8 system-ui,-apple-system,"PingFang SC","Microsoft YaHei",sans-serif}main{max-width:1120px;margin:auto;padding:24px}a{color:#236d54;text-underline-offset:3px;overflow-wrap:anywhere}h1{font-size:clamp(30px,5vw,48px);line-height:1.25;margin:15px 0}h2{font-size:26px;line-height:1.4;margin:0 0 18px}h3{font-size:20px;margin:10px 0}p{margin:10px 0}header{padding:30px 0 20px}.eyebrow{font-size:13px;letter-spacing:.16em;color:var(--accent)}.lede{font-size:19px;max-width:820px}.chips,.actions{display:flex;flex-wrap:wrap;gap:9px;margin:18px 0}.chip{padding:4px 12px;border:1px solid var(--line);border-radius:99px;font-size:13px;background:white}.action{display:inline-block;background:#e9efe6;padding:8px 13px;border-radius:9px;text-decoration:none;margin:4px 6px 4px 0;font-size:14px}section{background:#fff;border:1px solid var(--line);border-radius:18px;padding:28px;margin:20px 0}.gallery{display:grid;grid-template-columns:1.3fr 1fr;gap:18px;padding:0;border:0;background:none}.gallery figure{margin:0}img{display:block;width:100%;height:auto;object-fit:contain;border-radius:14px}.gallery figcaption,.source,.note,small{color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.grid section{margin:0}.alert{border-left:4px solid var(--accent);padding:12px 18px;background:#fff3e8}.orange{color:var(--accent)}table{width:100%;border-collapse:collapse;font-size:15px}td,th{text-align:left;vertical-align:top;padding:13px 10px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}td:first-child{min-width:120px}ol,ul{padding-left:22px}li{margin:10px 0}.steps{counter-reset:step}.steps li{padding-bottom:10px}.map{max-width:850px;margin:auto}.merchant{border-top:1px solid var(--line);padding:25px 0;scroll-margin-top:15px}.merchant:last-child{padding-bottom:0}dl{display:grid;grid-template-columns:125px 1fr;gap:8px 18px;font-size:15px}dt{color:var(--muted)}dd{margin:0}.route-flow{display:flex;gap:9px;flex-wrap:wrap;align-items:center;padding:18px;background:#eef3ec;border-radius:12px}.route-flow span{background:white;padding:9px 13px;border:1px solid var(--line);border-radius:9px}details summary{cursor:pointer;color:#236d54;font-weight:600}.foot{padding:20px 0;font-size:13px;color:var(--muted)}@media(max-width:680px){main{padding:15px}.gallery,.grid{grid-template-columns:1fr}section{padding:20px}header{padding-top:16px}dl{grid-template-columns:1fr;gap:2px}dd{margin-bottom:12px}td,th{padding:10px 6px;font-size:13px}td:first-child{min-width:85px}.lede{font-size:17px}}
</style></head><body><main><a href="../index.html">← 北京周末出行 · vibe trip</a><header><div class="eyebrow">WENYU RIVER · FAMILY CYCLING · 2026.10</div><h1>把上午交给绿道，<br>中午找地方好好坐下来。</h1><p class="lede">五道口自驾 → 温榆河来广营片区 → 原点收车 → 正餐或野餐。带自家自行车，不跨马路串园，不把午饭押在一间咖啡店上。</p><div class="chips"><span class="chip">P20首选 · P21备用</span><span class="chip">约6h含午饭 · 策划用时</span><span class="chip">亲子慢骑 · 分两段</span><span class="chip">资料核对：2026-10-10</span></div><div class="actions"><a class="action" href="#route">先看骑法</a><a class="action" href="#lunch">选午餐</a><a class="action" href="#map">看开放地图</a><a class="action" href="#merchants">查店址与来源</a></div></header>
<section class="gallery"><figure><img src="../assets/wenyu-cycling/report-2.webp" width="1920" height="1368" alt="北京日报报道配图：林荫路上的骑行队伍"><figcaption>林荫骑行氛围参考。<a href="REPORT">北京日报，2026-08-20，记者胡子傲</a>；报道未标明照片具体门区，不作为P20实拍证明。</figcaption></figure><figure><img src="../assets/wenyu-cycling/report-3.webp" width="802" height="527" alt="报道配图：水边建筑旁的骑行者"><figcaption>同一报道配图。建筑并未明确为某家咖啡馆，不据照片认店或规划路线。</figcaption></figure></section>
<div class="grid"><section><h2>一张行程卡</h2><table><tr><th>出发 / 自驾</th><td>五道口 → 北京温榆河公园-P20停车场；单程预留约1h（估算），具体距离、道路、拥堵以当天导航为准。</td></tr><tr><th>骑行主线</th><td>20号门 → 该入口内允许骑行的小环或折返段 → 同一入口 → P20。P21只作换起点方案，不强行骑行串联。</td></tr><tr><th>距离 / 强度</th><td>建议累计目标8—12km，可重复安全小环；这是体力目标，非核验的单圈里程。低强度优先，骑行时间约1.5h、分两段；准确长度及爬升未知。</td></tr><tr><th>装备 / 费用</th><td>自带普通自行车与儿童车、头盔。开放绿道免费免预约；停车收费未知；餐饮另计。</td></tr><tr><th>适合谁</th><td>能稳定刹车、转弯的亲子家庭；儿童只在允许的园内绿道骑，监护人全程陪同。</td></tr></table></section><section><h2>这条线为什么这样走</h2><p>温榆河公园体量大，但不是所有园区都允许自行车进入。<a href="OFFICIAL">北京市政府转载报道（2026-08-20）</a>确认：新开放<strong>8段、共14公里，分布在3个片区</strong>，并有环绿地和环湖的小环线。</p><p>从五道口来，不追全园打卡，选来广营片区就能把时间留给林荫、湿地和慢骑；大人前后照应，孩子累了随时收车。</p><p class="alert"><strong>14公里≠P20一条连续环线。</strong>18、20、21、22、23号门都是该片区入口，但各段之间的骑行连通性未核，不设计“20→21→23”穿越。</p><p>中午首选回原停车场装车，再去北苑／来广营吃正餐。想继续户外就带野餐；想喝咖啡则另开车去示范区，不让孩子骑公共道路追店。</p></section></div>
<section id="route"><h2>🚲 主线：原点收车，两段慢骑</h2><div class="route-flow" aria-label="行程逻辑示意，非地理比例地图"><span>五道口</span>→<span>自驾至P20</span>→<span>20号门内开放骑行段</span>↺<span>回P20装车</span>→<span>驾车午餐 / 原地野餐</span>→<span>五道口</span></div><p class="note">以上为行程逻辑示意，非GPS轨迹；不提供未经核实的转弯点或虚构GPX。</p><ol class="steps"><li><strong>先找停车场，不搜笼统“温榆河公园”。</strong>导航P20，满位才改P21；确认入口当天允许自带普通车和儿童车。停车区先推行，拍下车位、入口导览和厕所位置。</li><li><strong>从20号门进入，当场确认开放小环。</strong>沿明确允许骑行的园路慢骑；遇到无标识岔路、封闭、木栈道或公共道路接口，就在安全处折返。不能用地图上相邻的粉线猜连通。</li><li><strong>第一段45分钟，停15分钟。</strong>以熟悉路面与刹车为主，休息点选不挡通行的合法停留处。湿地只远观，不涉水、不贴河岸骑。</li><li><strong>第二段45分钟，回同一入口。</strong>体力好可重复已经确认的小环；累计8—12km只是可选目标，人多、风大或孩子疲劳就缩成4—6km或更短，11:30前收车优先。</li><li><strong>备选P21出发也执行同一原则。</strong>P21 → 21号门内现场开放段 → 原点返回。若两处均限行，改步行短游或返程午饭，不换到公共道路骑行。</li></ol><div>NAVPARK</div><p class="note">按钮是高德关键词检索入口，非已锁定坐标或实测路线。核对“北京／来广营／P20或P21”，勿误选P2、P9。</p></section>
<section id="map"><h2>开放边界：看原图，不猜路线</h2><p><a href="OFFICIAL">官方转载</a>列来广营入口<strong>18、20、21、22、23号门</strong>，配套<strong>P20或P21</strong>；原报道中粉色虚线为开放骑行区域。左下方为本次选择的片区。</p><figure class="map"><a href="../assets/wenyu-cycling/report-1.webp"><img src="../assets/wenyu-cycling/report-1.webp" width="1920" height="1590" alt="北京日报2026年8月开放骑行区域原图，粉色虚线，左下为18至23号入口" loading="lazy"></a><figcaption class="source">点图查看大图 · <a href="REPORT">北京日报客户端原报道配图</a>。编号是入口，停车场依据报道正文；图上无法确认20与21/22小环的内部连通关系。2026年8月开放信息不保证每个出行日都无临时管制。</figcaption></figure></section>
<section id="lunch"><h2>🍽️ 中午怎么选：三种吃法＋咖啡加餐</h2><p><strong>默认选A：</strong>把自行车装好再吃饭，少一次停车场往返。四家店址与证据在页末；当天营业和座位均需复核。</p><table><thead><tr><th>方案</th><th>适合什么情况</th><th>安排与边界</th></tr></thead><tbody><tr><td><strong>A · 室内正餐</strong><br>1.25h</td><td>孩子饿了、风大、想坐稳当</td><td><a href="#meizhou-beiyuan-huamao">眉州东坡（北苑华贸店）</a>优先候选，清河营南街华贸城。吃烤鸭／主食，点单确认不辣。楼内餐厅，不在园门口，先装车再导航。</td></tr><tr><td><strong>B · 中餐备选</strong><br>1—1.25h</td><td>想吃鱼、豆腐、饼，或A排队</td><td><a href="#redsun-laiguangying">红太阳美食生态园（来广营店）</a>，来广营新北路9号。散客接待、室内席位与宴会占场需询问，不能假定随到随坐。</td></tr><tr><td><strong>C · 自带野餐</strong><br>0.75—1h</td><td>晴好、想继续户外、少折腾</td><td>选当日允许停留的休息区；自带三明治／饭团、水果、保温水和坐垫。食物用保冷袋，垃圾带走，不生火、不堵骑行道。不保证固定野餐桌或草坪可入。</td></tr><tr><td><strong>咖啡加餐</strong><br>0.75h＋接驳</td><td>吃完不急着回家</td><td><a href="#double-u-wenyu">温榆·生活馆 Double U Coffee</a>在示范区片区。另驾车、步行入馆；不能视作P20/P21沿线补给，轻食与儿童饮品未知，不代替午饭。</td></tr></tbody></table><details><summary>想延续户外餐厅氛围？有一个谨慎候选</summary><p><a href="#shicao-wenyu">食草动物·炖锅烧烤·围炉煮茶</a>曾被北京时间报道为P2停车场东200米的户外主题餐厅。当前定位与营业尚未确认，且存在同名异地结果，<strong>只在核实门店后采用</strong>，否则直接选A/B/C。</p></details></section>
<section id="schedule"><h2>一天节奏｜08:30出发，14:30左右回家</h2><p class="note">以下6h为规划时间，不是实时导航或预约承诺。午餐选A/B；野餐可提前回家，咖啡则额外加时。</p><table><thead><tr><th>时间 / 时长</th><th>做什么</th><th>落地动作</th></tr></thead><tbody>SCHEDULE</tbody></table></section>
<section><h2>出发前的四件事</h2><ul><li><strong>准入：</strong>报道明确不允许共享单车、电动车、助力车、滑板、轮滑、成人滑板车和平衡车进入。自带普通自行车与合适的儿童自行车，不押宝现场租车。</li><li><strong>孩子不上公共道路：</strong>未满12岁不能在公共道路骑自行车，家长陪同也不例外（<a href="https://m.bjnews.com.cn/detail/1723636174129786.html">新京报，2024-08-14</a>）。停车区推行，跨片区用汽车，园内也须确认允许骑行、避让行人并控制速度。</li><li><strong>装备与天气：</strong>检查刹车、胎压、链条；全员头盔，带水、点心、补胎工具、薄外套。出行日未指定，本页不预报天气；临行查看北京气象预警与园方公告，雷雨、大风或积水改期。</li><li><strong>补给与午餐：</strong>厕所以现场导览／工作人员确认为准，未核到稳定营业的P20/P21沿线补给店。11:00前查店是否营业、是否有桌、停车入口；查不到就采用自带野餐或返程已确认营业的商场餐饮。</li></ul><p class="note">为什么不推荐P9泵道作为本次主线：这是另一项目与片区，不等于新开放绿道。为什么不串三大片区：路线连通未核、跨路接驳增加亲子风险，也挤占午饭和休息。</p></section>
<section id="merchants"><h2>餐饮信息卡｜地址、菜单线索与证据</h2><p class="note">这是按点评式结构整理的多源信息卡，不是大众点评实时数据。没有查到的评分、人均和营业状态保留未知；携程旧快照不冒充当前点评分。商户排序是行程适配建议，不是榜单排名。</p>CARDS</section><p class="foot">资料核对：2026-10-10 · 骑行开放证据：2026-08-20 · 当天开放与商户营业需临行复核。<br><a href="../data/wenyu-dining-research.json">餐饮研究记录 JSON</a> · <a href="../data/wenyu-official-source.json">开放报道存档</a> · <a href="../index.html">返回路线首页</a></p></main></body></html>'''
page=page.replace('NAVPARK',button('北京温榆河公园 P20停车场','导航检索：P20首选')+button('北京温榆河公园 P21停车场','导航检索：P21备用')).replace('SCHEDULE',schedule).replace('CARDS',''.join(cards)).replace('OFFICIAL',OFFICIAL).replace('REPORT',REPORT)
out=ROOT/'pages/wenyu-cycling-wudaokou.html'
out.write_text(page,encoding='utf-8')
print(json.dumps({'page':str(out),'merchant_count':len(cards),'schedule_minutes':sum(x[1] for x in rows)},ensure_ascii=False))
